<?php

namespace YukataRm\Laravel\Validation\Facades;

use Illuminate\Support\Facades\Facade;

/**
 * Validation Rules Facade
 *
 * @package YukataRm\Laravel\Validation\Facades
 *
 * @method static \YukataRm\Laravel\Validation\Interfaces\Rules\ValidationRulesInterface make(string $key)
 *
 * @method static \YukataRm\Laravel\Validation\Interfaces\Rules\ValidationRulesInterface addString(string $key, string $rule, string|null $message = null, mixed $values = [])
 * @method static \YukataRm\Laravel\Validation\Interfaces\Rules\ValidationRulesInterface addObject(string $key, string $ruleName, object $rule, string|null $message = null)
 *
 * @method static \YukataRm\Laravel\Validation\Interfaces\Rules\ValidationRulesInterface accepted(string $key, string|null $message = null)
 * @method static \YukataRm\Laravel\Validation\Interfaces\Rules\ValidationRulesInterface acceptedIf(string $field, mixed $value, string|null $message = null)
 * @method static \YukataRm\Laravel\Validation\Interfaces\Rules\ValidationRulesInterface activeUrl(string $key, string|null $message = null)
 * @method static \YukataRm\Laravel\Validation\Interfaces\Rules\ValidationRulesInterface after(string $key, string $date, string|null $message = null)
 * @method static \YukataRm\Laravel\Validation\Interfaces\Rules\ValidationRulesInterface afterOrEqual(string $key, string $date, string|null $message = null)
 * @method static \YukataRm\Laravel\Validation\Interfaces\Rules\ValidationRulesInterface alpha(string $key, bool $isAscii = false, string|null $message = null)
 * @method static \YukataRm\Laravel\Validation\Interfaces\Rules\ValidationRulesInterface alphaDash(string $key, bool $isAscii = false, string|null $message = null)
 * @method static \YukataRm\Laravel\Validation\Interfaces\Rules\ValidationRulesInterface alphaNum(string $key, bool $isAscii = false, string|null $message = null)
 * @method static \YukataRm\Laravel\Validation\Interfaces\Rules\ValidationRulesInterface array(string $key, array|string $acceptKeys = [], string|null $message = null)
 * @method static \YukataRm\Laravel\Validation\Interfaces\Rules\ValidationRulesInterface ascii(string $key, string|null $message = null)
 * @method static \YukataRm\Laravel\Validation\Interfaces\Rules\ValidationRulesInterface bail(string $key, string|null $message = null)
 * @method static \YukataRm\Laravel\Validation\Interfaces\Rules\ValidationRulesInterface before(string $key, string $date, string|null $message = null)
 * @method static \YukataRm\Laravel\Validation\Interfaces\Rules\ValidationRulesInterface beforeOrEqual(string $key, string $date, string|null $message = null)
 * @method static \YukataRm\Laravel\Validation\Interfaces\Rules\ValidationRulesInterface between(string $key, int $min, int $max, string|null $message = null)
 * @method static \YukataRm\Laravel\Validation\Interfaces\Rules\ValidationRulesInterface boolean(string $key, string|null $message = null)
 * @method static \YukataRm\Laravel\Validation\Interfaces\Rules\ValidationRulesInterface confirmed(string $key, array|string $values, string|null $message = null)
 * @method static \YukataRm\Laravel\Validation\Interfaces\Rules\ValidationRulesInterface contains(string $key, string|null $message = null)
 * @method static \YukataRm\Laravel\Validation\Interfaces\Rules\ValidationRulesInterface currentPassword(string $key, string $guard = "web", string|null $message = null)
 * @method static \YukataRm\Laravel\Validation\Interfaces\Rules\ValidationRulesInterface date(string $key, string|null $message = null)
 * @method static \YukataRm\Laravel\Validation\Interfaces\Rules\ValidationRulesInterface dateEqual(string $key, string $date, string|null $message = null)
 * @method static \YukataRm\Laravel\Validation\Interfaces\Rules\ValidationRulesInterface dateFormat(string $key, string $format, string|null $message = null)
 * @method static \YukataRm\Laravel\Validation\Interfaces\Rules\ValidationRulesInterface decimal(string $key, int $min, int|null $max = null, string|null $message = null)
 * @method static \YukataRm\Laravel\Validation\Interfaces\Rules\ValidationRulesInterface declined(string $key, string|null $message = null)
 * @method static \YukataRm\Laravel\Validation\Interfaces\Rules\ValidationRulesInterface declinedIf(string $key, string $field, mixed $value, string|null $message = null)
 * @method static \YukataRm\Laravel\Validation\Interfaces\Rules\ValidationRulesInterface different(string $key, string $field, string|null $message = null)
 * @method static \YukataRm\Laravel\Validation\Interfaces\Rules\ValidationRulesInterface digits(string $key, int $min, string|null $message = null)
 * @method static \YukataRm\Laravel\Validation\Interfaces\Rules\ValidationRulesInterface digitsBetween(string $key, int $min, int $max, string|null $message = null)
 * @method static \YukataRm\Laravel\Validation\Interfaces\Rules\ValidationRulesInterface dimensions(string $key, int|null $width = null, int|null $height = null, int|null $minWidth = null, int|null $minHeight = null, int|null $maxWidth = null, int|null $maxHeight = null, float|string|null $ratio = null, string|null $message = null)
 * @method static \YukataRm\Laravel\Validation\Interfaces\Rules\ValidationRulesInterface distinct(string $key, bool $strict = false, bool $ignoreCase = false, string|null $message = null)
 * @method static \YukataRm\Laravel\Validation\Interfaces\Rules\ValidationRulesInterface doesntStartWith(string $key, array|string $values, string|null $message = null)
 * @method static \YukataRm\Laravel\Validation\Interfaces\Rules\ValidationRulesInterface doesntEndWith(string $key, array|string $values, string|null $message = null)
 * @method static \YukataRm\Laravel\Validation\Interfaces\Rules\ValidationRulesInterface email(string $key, string|null $message = null)
 * @method static \YukataRm\Laravel\Validation\Interfaces\Rules\ValidationRulesInterface endsWith(string $key, array|string $values, string|null $message = null)
 * @method static \YukataRm\Laravel\Validation\Interfaces\Rules\ValidationRulesInterface enum(string $key, string $enum, \Closure|null $callback = null, string|null $message = null)
 * @method static \YukataRm\Laravel\Validation\Interfaces\Rules\ValidationRulesInterface exclude(string $key, string|null $message = null)
 * @method static \YukataRm\Laravel\Validation\Interfaces\Rules\ValidationRulesInterface excludeIf(string $key, string $field, mixed $value, string|null $message = null)
 * @method static \YukataRm\Laravel\Validation\Interfaces\Rules\ValidationRulesInterface excludeUnless(string $key, string $field, mixed $value, string|null $message = null)
 * @method static \YukataRm\Laravel\Validation\Interfaces\Rules\ValidationRulesInterface excludeWith(string $key, array|string $fields, string|null $message = null)
 * @method static \YukataRm\Laravel\Validation\Interfaces\Rules\ValidationRulesInterface excludeWithout(string $key, string $field, string|null $message = null)
 * @method static \YukataRm\Laravel\Validation\Interfaces\Rules\ValidationRulesInterface exists(string $key, string $table, string|null $column = null, \Closure|null $callback = null, string|null $message = null)
 * @method static \YukataRm\Laravel\Validation\Interfaces\Rules\ValidationRulesInterface extensions(string $key, array|string $extensions, string|null $message = null)
 * @method static \YukataRm\Laravel\Validation\Interfaces\Rules\ValidationRulesInterface file(string $key, string|null $message = null)
 * @method static \YukataRm\Laravel\Validation\Interfaces\Rules\ValidationRulesInterface filled(string $key, string|null $message = null)
 * @method static \YukataRm\Laravel\Validation\Interfaces\Rules\ValidationRulesInterface gt(string $key, string $field, string|null $message = null)
 * @method static \YukataRm\Laravel\Validation\Interfaces\Rules\ValidationRulesInterface gte(string $key, string $field, string|null $message = null)
 * @method static \YukataRm\Laravel\Validation\Interfaces\Rules\ValidationRulesInterface hexColor(string $key, string|null $message = null)
 * @method static \YukataRm\Laravel\Validation\Interfaces\Rules\ValidationRulesInterface image(string $key, string|null $message = null)
 * @method static \YukataRm\Laravel\Validation\Interfaces\Rules\ValidationRulesInterface in(string $key, array|string $values, string|null $message = null)
 * @method static \YukataRm\Laravel\Validation\Interfaces\Rules\ValidationRulesInterface inArray(string $key, string $field, string $key, string|null $message = null)
 * @method static \YukataRm\Laravel\Validation\Interfaces\Rules\ValidationRulesInterface integer(string $key, string|null $message = null)
 * @method static \YukataRm\Laravel\Validation\Interfaces\Rules\ValidationRulesInterface ip(string $key, string|null $message = null)
 * @method static \YukataRm\Laravel\Validation\Interfaces\Rules\ValidationRulesInterface ipv4(string $key, string|null $message = null)
 * @method static \YukataRm\Laravel\Validation\Interfaces\Rules\ValidationRulesInterface ipv6(string $key, string|null $message = null)
 * @method static \YukataRm\Laravel\Validation\Interfaces\Rules\ValidationRulesInterface json(string $key, string|null $message = null)
 * @method static \YukataRm\Laravel\Validation\Interfaces\Rules\ValidationRulesInterface lt(string $key, string $field, string|null $message = null)
 * @method static \YukataRm\Laravel\Validation\Interfaces\Rules\ValidationRulesInterface lte(string $key, string $field, string|null $message = null)
 * @method static \YukataRm\Laravel\Validation\Interfaces\Rules\ValidationRulesInterface lowercase(string $key, string|null $message = null)
 * @method static \YukataRm\Laravel\Validation\Interfaces\Rules\ValidationRulesInterface list(string $key, string|null $message = null)
 * @method static \YukataRm\Laravel\Validation\Interfaces\Rules\ValidationRulesInterface macAddress(string $key, string|null $message = null)
 * @method static \YukataRm\Laravel\Validation\Interfaces\Rules\ValidationRulesInterface max(string $key, int $max, string|null $message = null)
 * @method static \YukataRm\Laravel\Validation\Interfaces\Rules\ValidationRulesInterface maxDigits(string $key, int $max, string|null $message = null)
 * @method static \YukataRm\Laravel\Validation\Interfaces\Rules\ValidationRulesInterface mimetypes(string $key, array|string $mimetypes, string|null $message = null)
 * @method static \YukataRm\Laravel\Validation\Interfaces\Rules\ValidationRulesInterface mimes(string $key, array|string $extensions, string|null $message = null)
 * @method static \YukataRm\Laravel\Validation\Interfaces\Rules\ValidationRulesInterface min(string $key, int $min, string|null $message = null)
 * @method static \YukataRm\Laravel\Validation\Interfaces\Rules\ValidationRulesInterface minDigits(string $key, int $min, string|null $message = null)
 * @method static \YukataRm\Laravel\Validation\Interfaces\Rules\ValidationRulesInterface multipleOf(string $key, int $num, string|null $message = null)
 * @method static \YukataRm\Laravel\Validation\Interfaces\Rules\ValidationRulesInterface missing(string $key, string|null $message = null)
 * @method static \YukataRm\Laravel\Validation\Interfaces\Rules\ValidationRulesInterface missingIf(string $key, string $field, array $values, string|null $message = null)
 * @method static \YukataRm\Laravel\Validation\Interfaces\Rules\ValidationRulesInterface missingUnless(string $key, string $field, array $values, string|null $message = null)
 * @method static \YukataRm\Laravel\Validation\Interfaces\Rules\ValidationRulesInterface missingWith(string $key, array|string $fields, string|null $message = null)
 * @method static \YukataRm\Laravel\Validation\Interfaces\Rules\ValidationRulesInterface missingWithAll(string $key, array|string $fields, string|null $message = null)
 * @method static \YukataRm\Laravel\Validation\Interfaces\Rules\ValidationRulesInterface notIn(string $key, array|string $values, string|null $message = null)
 * @method static \YukataRm\Laravel\Validation\Interfaces\Rules\ValidationRulesInterface notRegex(string $key, string $pattern, string|null $message = null)
 * @method static \YukataRm\Laravel\Validation\Interfaces\Rules\ValidationRulesInterface nullable(string $key, string|null $message = null)
 * @method static \YukataRm\Laravel\Validation\Interfaces\Rules\ValidationRulesInterface numeric(string $key, string|null $message = null)
 * @method static \YukataRm\Laravel\Validation\Interfaces\Rules\ValidationRulesInterface present(string $key, string|null $message = null)
 * @method static \YukataRm\Laravel\Validation\Interfaces\Rules\ValidationRulesInterface presentIf(string $key, string $field, mixed $value, string|null $message = null)
 * @method static \YukataRm\Laravel\Validation\Interfaces\Rules\ValidationRulesInterface presentUnless(string $key, string $field, mixed $value, string|null $message = null)
 * @method static \YukataRm\Laravel\Validation\Interfaces\Rules\ValidationRulesInterface presentWith(string $key, string $field, string|null $message = null)
 * @method static \YukataRm\Laravel\Validation\Interfaces\Rules\ValidationRulesInterface presentWithAll(string $key, array|string $fields, string|null $message = null)
 * @method static \YukataRm\Laravel\Validation\Interfaces\Rules\ValidationRulesInterface prohibited(string $key, string|null $message = null)
 * @method static \YukataRm\Laravel\Validation\Interfaces\Rules\ValidationRulesInterface prohibitedIf(string $key, string $field, array $values, string|null $message = null)
 * @method static \YukataRm\Laravel\Validation\Interfaces\Rules\ValidationRulesInterface prohibitedUnless(string $key, string $field, array $values, string|null $message = null)
 * @method static \YukataRm\Laravel\Validation\Interfaces\Rules\ValidationRulesInterface prohibits(string $key, array|string $fields, string|null $message = null)
 * @method static \YukataRm\Laravel\Validation\Interfaces\Rules\ValidationRulesInterface regex(string $key, string $pattern, string|null $message = null)
 * @method static \YukataRm\Laravel\Validation\Interfaces\Rules\ValidationRulesInterface required(string $key, string|null $message = null)
 * @method static \YukataRm\Laravel\Validation\Interfaces\Rules\ValidationRulesInterface requiredIf(string $key, string $field, mixed $value, string|null $message = null)
 * @method static \YukataRm\Laravel\Validation\Interfaces\Rules\ValidationRulesInterface requiredIfAccepted(string $key, array|string $fields, string|null $message = null)
 * @method static \YukataRm\Laravel\Validation\Interfaces\Rules\ValidationRulesInterface requiredIfDeclined(string $key, array|string $fields, string|null $message = null)
 * @method static \YukataRm\Laravel\Validation\Interfaces\Rules\ValidationRulesInterface requiredUnless(string $key, string $field, mixed $value, string|null $message = null)
 * @method static \YukataRm\Laravel\Validation\Interfaces\Rules\ValidationRulesInterface requiredWith(string $key, array|string $fields, string|null $message = null)
 * @method static \YukataRm\Laravel\Validation\Interfaces\Rules\ValidationRulesInterface requiredWithAll(string $key, array|string $fields, string|null $message = null)
 * @method static \YukataRm\Laravel\Validation\Interfaces\Rules\ValidationRulesInterface requiredWithout(string $key, array|string $fields, string|null $message = null)
 * @method static \YukataRm\Laravel\Validation\Interfaces\Rules\ValidationRulesInterface requiredWithoutAll(string $key, array|string $fields, string|null $message = null)
 * @method static \YukataRm\Laravel\Validation\Interfaces\Rules\ValidationRulesInterface requiredArrayKeys(string $key, array|string $keys, string|null $message = null)
 * @method static \YukataRm\Laravel\Validation\Interfaces\Rules\ValidationRulesInterface same(string $key, string $field, string|null $message = null)
 * @method static \YukataRm\Laravel\Validation\Interfaces\Rules\ValidationRulesInterface size(string $key, int $size, string|null $message = null)
 * @method static \YukataRm\Laravel\Validation\Interfaces\Rules\ValidationRulesInterface startsWith(string $key, array|string $values, string|null $message = null)
 * @method static \YukataRm\Laravel\Validation\Interfaces\Rules\ValidationRulesInterface string(string $key, string|null $message = null)
 * @method static \YukataRm\Laravel\Validation\Interfaces\Rules\ValidationRulesInterface timezone(string $key, array|string $identifiers = [], string|null $message = null)
 * @method static \YukataRm\Laravel\Validation\Interfaces\Rules\ValidationRulesInterface unique(string $key, string $table, string|null $column = null, \Closure|null $callback = null, string|null $message = null)
 * @method static \YukataRm\Laravel\Validation\Interfaces\Rules\ValidationRulesInterface uppercase(string $key, string|null $message = null)
 * @method static \YukataRm\Laravel\Validation\Interfaces\Rules\ValidationRulesInterface url(string $key, string|null $message = null)
 * @method static \YukataRm\Laravel\Validation\Interfaces\Rules\ValidationRulesInterface ulid(string $key, string|null $message = null)
 * @method static \YukataRm\Laravel\Validation\Interfaces\Rules\ValidationRulesInterface uuid(string $key, string|null $message = null)
 *
 * @method static \YukataRm\Laravel\Validation\Interfaces\Rules\ValidationRulesInterface flag(string $key, string|null $message = null)
 * @method static \YukataRm\Laravel\Validation\Interfaces\Rules\ValidationRulesInterface asDate(string $key, string|null $message = null)
 * @method static \YukataRm\Laravel\Validation\Interfaces\Rules\ValidationRulesInterface asTime(string $key, string|null $message = null)
 * @method static \YukataRm\Laravel\Validation\Interfaces\Rules\ValidationRulesInterface asDateTime(string $key, string|null $message = null)
 * @method static \YukataRm\Laravel\Validation\Interfaces\Rules\ValidationRulesInterface asYearMonth(string $key, string|null $message = null)
 * @method static \YukataRm\Laravel\Validation\Interfaces\Rules\ValidationRulesInterface asMonthDay(string $key, string|null $message = null)
 * @method static \YukataRm\Laravel\Validation\Interfaces\Rules\ValidationRulesInterface asHourMinute(string $key, string|null $message = null)
 * @method static \YukataRm\Laravel\Validation\Interfaces\Rules\ValidationRulesInterface asMinuteSecond(string $key, string|null $message = null)
 * @method static \YukataRm\Laravel\Validation\Interfaces\Rules\ValidationRulesInterface asYear(string $key, string|null $message = null)
 * @method static \YukataRm\Laravel\Validation\Interfaces\Rules\ValidationRulesInterface asMonth(string $key, string|null $message = null)
 * @method static \YukataRm\Laravel\Validation\Interfaces\Rules\ValidationRulesInterface asMonthZero(string $key, string|null $message = null)
 * @method static \YukataRm\Laravel\Validation\Interfaces\Rules\ValidationRulesInterface asMonthName(string $key, string|null $message = null)
 * @method static \YukataRm\Laravel\Validation\Interfaces\Rules\ValidationRulesInterface asMonthNameShort(string $key, string|null $message = null)
 * @method static \YukataRm\Laravel\Validation\Interfaces\Rules\ValidationRulesInterface asDay(string $key, string|null $message = null)
 * @method static \YukataRm\Laravel\Validation\Interfaces\Rules\ValidationRulesInterface asDayZero(string $key, string|null $message = null)
 * @method static \YukataRm\Laravel\Validation\Interfaces\Rules\ValidationRulesInterface asHour(string $key, string|null $message = null)
 * @method static \YukataRm\Laravel\Validation\Interfaces\Rules\ValidationRulesInterface asHourZero(string $key, string|null $message = null)
 * @method static \YukataRm\Laravel\Validation\Interfaces\Rules\ValidationRulesInterface asHourTwelveNotation(string $key, string|null $message = null)
 * @method static \YukataRm\Laravel\Validation\Interfaces\Rules\ValidationRulesInterface asHourTwelveNotationZero(string $key, string|null $message = null)
 * @method static \YukataRm\Laravel\Validation\Interfaces\Rules\ValidationRulesInterface asMinute(string $key, string|null $message = null)
 * @method static \YukataRm\Laravel\Validation\Interfaces\Rules\ValidationRulesInterface asSecond(string $key, string|null $message = null)
 * @method static \YukataRm\Laravel\Validation\Interfaces\Rules\ValidationRulesInterface existsNotDeleted(string $key, string $table, string|null $column = null, string $deletedAtColumn = "deleted_at", string|null $message = null)
 * @method static \YukataRm\Laravel\Validation\Interfaces\Rules\ValidationRulesInterface existsDeleted(string $key, string $table, string|null $column = null, string $deletedAtColumn = "deleted_at", string|null $message = null)
 * @method static \YukataRm\Laravel\Validation\Interfaces\Rules\ValidationRulesInterface id(string $key, string $table, string|null $message = null)
 * @method static \YukataRm\Laravel\Validation\Interfaces\Rules\ValidationRulesInterface tel(string $key, string|null $message = null)
 * @method static \YukataRm\Laravel\Validation\Interfaces\Rules\ValidationRulesInterface postCode(string $key, string|null $message = null)
 * @method static \YukataRm\Laravel\Validation\Interfaces\Rules\ValidationRulesInterface uniqueNotDeleted(string $key, string $table, string|null $column = null, string $deletedAtColumn = "deleted_at", string|null $message = null)
 * @method static \YukataRm\Laravel\Validation\Interfaces\Rules\ValidationRulesInterface uniqueDeleted(string $key, string $table, string|null $column = null, string $deletedAtColumn = "deleted_at", string|null $message = null)
 * @method static \YukataRm\Laravel\Validation\Interfaces\Rules\ValidationRulesInterface uniqueIgnore(string $key, string $table, string|null $column = null, mixed $ignore = null, string $ignoreColumn = "id", string|null $message = null)
 * @method static \YukataRm\Laravel\Validation\Interfaces\Rules\ValidationRulesInterface uniqueIgnoreNotDeleted(string $key, string $table, string|null $column = null, mixed $ignore = null, string $ignoreColumn = "id", string $deletedAtColumn = "deleted_at", string|null $message = null)
 * @method static \YukataRm\Laravel\Validation\Interfaces\Rules\ValidationRulesInterface uniqueIgnoreDeleted(string $key, string $table, string|null $column = null, mixed $ignore = null, string $ignoreColumn = "id", string $deletedAtColumn = "deleted_at", string|null $message = null)
 *
 * @see \YukataRm\Laravel\Validation\Facades\Managers\RulesManager
 */
class Rules extends Facade
{
    /**
     * Facade Accessor
     *
     * @return string
     */
    protected static function getFacadeAccessor(): string
    {
        return static::class;
    }
}
