<?php

namespace YukataRm\Laravel\Validation\Facade;

use Illuminate\Support\Facades\Facade;

/**
 * Validation Rules Facade
 * 
 * @package YukataRm\Laravel\Validation\Facade
 * 
 * @method static \YukataRm\Laravel\Validation\Interface\ValidationRulesInterface make(string $key)
 * 
 * @method static \YukataRm\Laravel\Validation\Interface\ValidationRulesInterface addString(string $key, string $rule, string|null $message = null, mixed $values = [])
 * @method static \YukataRm\Laravel\Validation\Interface\ValidationRulesInterface addObject(string $key, string $ruleName, object $rule, string|null $message = null)
 * 
 * @method static \YukataRm\Laravel\Validation\Interface\ValidationRulesInterface accepted(string $key, string|null $message = null)
 * @method static \YukataRm\Laravel\Validation\Interface\ValidationRulesInterface acceptedIf(string $field, mixed $value, string|null $message = null)
 * @method static \YukataRm\Laravel\Validation\Interface\ValidationRulesInterface activeUrl(string $key, string|null $message = null)
 * @method static \YukataRm\Laravel\Validation\Interface\ValidationRulesInterface after(string $key, string $date, string|null $message = null)
 * @method static \YukataRm\Laravel\Validation\Interface\ValidationRulesInterface afterOrEqual(string $key, string $date, string|null $message = null)
 * @method static \YukataRm\Laravel\Validation\Interface\ValidationRulesInterface alpha(string $key, bool $isAscii = false, string|null $message = null)
 * @method static \YukataRm\Laravel\Validation\Interface\ValidationRulesInterface alphaDash(string $key, bool $isAscii = false, string|null $message = null)
 * @method static \YukataRm\Laravel\Validation\Interface\ValidationRulesInterface alphaNum(string $key, bool $isAscii = false, string|null $message = null)
 * @method static \YukataRm\Laravel\Validation\Interface\ValidationRulesInterface array(string $key, array|string $acceptKeys = [], string|null $message = null)
 * @method static \YukataRm\Laravel\Validation\Interface\ValidationRulesInterface ascii(string $key, string|null $message = null)
 * @method static \YukataRm\Laravel\Validation\Interface\ValidationRulesInterface bail(string $key, string|null $message = null)
 * @method static \YukataRm\Laravel\Validation\Interface\ValidationRulesInterface before(string $key, string $date, string|null $message = null)
 * @method static \YukataRm\Laravel\Validation\Interface\ValidationRulesInterface beforeOrEqual(string $key, string $date, string|null $message = null)
 * @method static \YukataRm\Laravel\Validation\Interface\ValidationRulesInterface between(string $key, int $min, int $max, string|null $message = null)
 * @method static \YukataRm\Laravel\Validation\Interface\ValidationRulesInterface boolean(string $key, string|null $message = null)
 * @method static \YukataRm\Laravel\Validation\Interface\ValidationRulesInterface confirmed(string $key, array|string $values, string|null $message = null)
 * @method static \YukataRm\Laravel\Validation\Interface\ValidationRulesInterface contains(string $key, string|null $message = null)
 * @method static \YukataRm\Laravel\Validation\Interface\ValidationRulesInterface currentPassword(string $key, string $guard = "web", string|null $message = null)
 * @method static \YukataRm\Laravel\Validation\Interface\ValidationRulesInterface date(string $key, string|null $message = null)
 * @method static \YukataRm\Laravel\Validation\Interface\ValidationRulesInterface dateEqual(string $key, string $date, string|null $message = null)
 * @method static \YukataRm\Laravel\Validation\Interface\ValidationRulesInterface dateFormat(string $key, string $format, string|null $message = null)
 * @method static \YukataRm\Laravel\Validation\Interface\ValidationRulesInterface decimal(string $key, int $min, int|null $max = null, string|null $message = null)
 * @method static \YukataRm\Laravel\Validation\Interface\ValidationRulesInterface declined(string $key, string|null $message = null)
 * @method static \YukataRm\Laravel\Validation\Interface\ValidationRulesInterface declinedIf(string $key, string $field, mixed $value, string|null $message = null)
 * @method static \YukataRm\Laravel\Validation\Interface\ValidationRulesInterface different(string $key, string $field, string|null $message = null)
 * @method static \YukataRm\Laravel\Validation\Interface\ValidationRulesInterface digits(string $key, int $min, string|null $message = null)
 * @method static \YukataRm\Laravel\Validation\Interface\ValidationRulesInterface digitsBetween(string $key, int $min, int $max, string|null $message = null)
 * @method static \YukataRm\Laravel\Validation\Interface\ValidationRulesInterface dimensions(string $key, int|null $width = null, int|null $height = null, int|null $minWidth = null, int|null $minHeight = null, int|null $maxWidth = null, int|null $maxHeight = null, float|string|null $ratio = null, string|null $message = null)
 * @method static \YukataRm\Laravel\Validation\Interface\ValidationRulesInterface distinct(string $key, bool $strict = false, bool $ignoreCase = false, string|null $message = null)
 * @method static \YukataRm\Laravel\Validation\Interface\ValidationRulesInterface doesntStartWith(string $key, array|string $values, string|null $message = null)
 * @method static \YukataRm\Laravel\Validation\Interface\ValidationRulesInterface doesntEndWith(string $key, array|string $values, string|null $message = null)
 * @method static \YukataRm\Laravel\Validation\Interface\ValidationRulesInterface email(string $key, string|null $message = null)
 * @method static \YukataRm\Laravel\Validation\Interface\ValidationRulesInterface endsWith(string $key, array|string $values, string|null $message = null)
 * @method static \YukataRm\Laravel\Validation\Interface\ValidationRulesInterface enum(string $key, string $enum, \Closure|null $callback = null, string|null $message = null)
 * @method static \YukataRm\Laravel\Validation\Interface\ValidationRulesInterface exclude(string $key, string|null $message = null)
 * @method static \YukataRm\Laravel\Validation\Interface\ValidationRulesInterface excludeIf(string $key, string $field, mixed $value, string|null $message = null)
 * @method static \YukataRm\Laravel\Validation\Interface\ValidationRulesInterface excludeUnless(string $key, string $field, mixed $value, string|null $message = null)
 * @method static \YukataRm\Laravel\Validation\Interface\ValidationRulesInterface excludeWith(string $key, array|string $fields, string|null $message = null)
 * @method static \YukataRm\Laravel\Validation\Interface\ValidationRulesInterface excludeWithout(string $key, string $field, string|null $message = null)
 * @method static \YukataRm\Laravel\Validation\Interface\ValidationRulesInterface exists(string $key, string $table, string|null $column = null, \Closure|null $callback = null, string|null $message = null)
 * @method static \YukataRm\Laravel\Validation\Interface\ValidationRulesInterface extensions(string $key, array|string $extensions, string|null $message = null)
 * @method static \YukataRm\Laravel\Validation\Interface\ValidationRulesInterface file(string $key, string|null $message = null)
 * @method static \YukataRm\Laravel\Validation\Interface\ValidationRulesInterface filled(string $key, string|null $message = null)
 * @method static \YukataRm\Laravel\Validation\Interface\ValidationRulesInterface gt(string $key, string $field, string|null $message = null)
 * @method static \YukataRm\Laravel\Validation\Interface\ValidationRulesInterface gte(string $key, string $field, string|null $message = null)
 * @method static \YukataRm\Laravel\Validation\Interface\ValidationRulesInterface hexColor(string $key, string|null $message = null)
 * @method static \YukataRm\Laravel\Validation\Interface\ValidationRulesInterface image(string $key, string|null $message = null)
 * @method static \YukataRm\Laravel\Validation\Interface\ValidationRulesInterface in(string $key, array|string $values, string|null $message = null)
 * @method static \YukataRm\Laravel\Validation\Interface\ValidationRulesInterface inArray(string $key, string $field, string $key, string|null $message = null)
 * @method static \YukataRm\Laravel\Validation\Interface\ValidationRulesInterface integer(string $key, string|null $message = null)
 * @method static \YukataRm\Laravel\Validation\Interface\ValidationRulesInterface ip(string $key, string|null $message = null)
 * @method static \YukataRm\Laravel\Validation\Interface\ValidationRulesInterface ipv4(string $key, string|null $message = null)
 * @method static \YukataRm\Laravel\Validation\Interface\ValidationRulesInterface ipv6(string $key, string|null $message = null)
 * @method static \YukataRm\Laravel\Validation\Interface\ValidationRulesInterface json(string $key, string|null $message = null)
 * @method static \YukataRm\Laravel\Validation\Interface\ValidationRulesInterface lt(string $key, string $field, string|null $message = null)
 * @method static \YukataRm\Laravel\Validation\Interface\ValidationRulesInterface lte(string $key, string $field, string|null $message = null)
 * @method static \YukataRm\Laravel\Validation\Interface\ValidationRulesInterface lowercase(string $key, string|null $message = null)
 * @method static \YukataRm\Laravel\Validation\Interface\ValidationRulesInterface list(string $key, string|null $message = null)
 * @method static \YukataRm\Laravel\Validation\Interface\ValidationRulesInterface macAddress(string $key, string|null $message = null)
 * @method static \YukataRm\Laravel\Validation\Interface\ValidationRulesInterface max(string $key, int $max, string|null $message = null)
 * @method static \YukataRm\Laravel\Validation\Interface\ValidationRulesInterface maxDigits(string $key, int $max, string|null $message = null)
 * @method static \YukataRm\Laravel\Validation\Interface\ValidationRulesInterface mimetypes(string $key, array|string $mimetypes, string|null $message = null)
 * @method static \YukataRm\Laravel\Validation\Interface\ValidationRulesInterface mimes(string $key, array|string $extensions, string|null $message = null)
 * @method static \YukataRm\Laravel\Validation\Interface\ValidationRulesInterface min(string $key, int $min, string|null $message = null)
 * @method static \YukataRm\Laravel\Validation\Interface\ValidationRulesInterface minDigits(string $key, int $min, string|null $message = null)
 * @method static \YukataRm\Laravel\Validation\Interface\ValidationRulesInterface multipleOf(string $key, int $num, string|null $message = null)
 * @method static \YukataRm\Laravel\Validation\Interface\ValidationRulesInterface missing(string $key, string|null $message = null)
 * @method static \YukataRm\Laravel\Validation\Interface\ValidationRulesInterface missingIf(string $key, string $field, array $values, string|null $message = null)
 * @method static \YukataRm\Laravel\Validation\Interface\ValidationRulesInterface missingUnless(string $key, string $field, array $values, string|null $message = null)
 * @method static \YukataRm\Laravel\Validation\Interface\ValidationRulesInterface missingWith(string $key, array|string $fields, string|null $message = null)
 * @method static \YukataRm\Laravel\Validation\Interface\ValidationRulesInterface missingWithAll(string $key, array|string $fields, string|null $message = null)
 * @method static \YukataRm\Laravel\Validation\Interface\ValidationRulesInterface notIn(string $key, array|string $values, string|null $message = null)
 * @method static \YukataRm\Laravel\Validation\Interface\ValidationRulesInterface notRegex(string $key, string $pattern, string|null $message = null)
 * @method static \YukataRm\Laravel\Validation\Interface\ValidationRulesInterface nullable(string $key, string|null $message = null)
 * @method static \YukataRm\Laravel\Validation\Interface\ValidationRulesInterface numeric(string $key, string|null $message = null)
 * @method static \YukataRm\Laravel\Validation\Interface\ValidationRulesInterface present(string $key, string|null $message = null)
 * @method static \YukataRm\Laravel\Validation\Interface\ValidationRulesInterface presentIf(string $key, string $field, mixed $value, string|null $message = null)
 * @method static \YukataRm\Laravel\Validation\Interface\ValidationRulesInterface presentUnless(string $key, string $field, mixed $value, string|null $message = null)
 * @method static \YukataRm\Laravel\Validation\Interface\ValidationRulesInterface presentWith(string $key, string $field, string|null $message = null)
 * @method static \YukataRm\Laravel\Validation\Interface\ValidationRulesInterface presentWithAll(string $key, array|string $fields, string|null $message = null)
 * @method static \YukataRm\Laravel\Validation\Interface\ValidationRulesInterface prohibited(string $key, string|null $message = null)
 * @method static \YukataRm\Laravel\Validation\Interface\ValidationRulesInterface prohibitedIf(string $key, string $field, array $values, string|null $message = null)
 * @method static \YukataRm\Laravel\Validation\Interface\ValidationRulesInterface prohibitedUnless(string $key, string $field, array $values, string|null $message = null)
 * @method static \YukataRm\Laravel\Validation\Interface\ValidationRulesInterface prohibits(string $key, array|string $fields, string|null $message = null)
 * @method static \YukataRm\Laravel\Validation\Interface\ValidationRulesInterface regex(string $key, string $pattern, string|null $message = null)
 * @method static \YukataRm\Laravel\Validation\Interface\ValidationRulesInterface required(string $key, string|null $message = null)
 * @method static \YukataRm\Laravel\Validation\Interface\ValidationRulesInterface requiredIf(string $key, string $field, mixed $value, string|null $message = null)
 * @method static \YukataRm\Laravel\Validation\Interface\ValidationRulesInterface requiredIfAccepted(string $key, array|string $fields, string|null $message = null)
 * @method static \YukataRm\Laravel\Validation\Interface\ValidationRulesInterface requiredIfDeclined(string $key, array|string $fields, string|null $message = null)
 * @method static \YukataRm\Laravel\Validation\Interface\ValidationRulesInterface requiredUnless(string $key, string $field, mixed $value, string|null $message = null)
 * @method static \YukataRm\Laravel\Validation\Interface\ValidationRulesInterface requiredWith(string $key, array|string $fields, string|null $message = null)
 * @method static \YukataRm\Laravel\Validation\Interface\ValidationRulesInterface requiredWithAll(string $key, array|string $fields, string|null $message = null)
 * @method static \YukataRm\Laravel\Validation\Interface\ValidationRulesInterface requiredWithout(string $key, array|string $fields, string|null $message = null)
 * @method static \YukataRm\Laravel\Validation\Interface\ValidationRulesInterface requiredWithoutAll(string $key, array|string $fields, string|null $message = null)
 * @method static \YukataRm\Laravel\Validation\Interface\ValidationRulesInterface requiredArrayKeys(string $key, array|string $keys, string|null $message = null)
 * @method static \YukataRm\Laravel\Validation\Interface\ValidationRulesInterface same(string $key, string $field, string|null $message = null)
 * @method static \YukataRm\Laravel\Validation\Interface\ValidationRulesInterface size(string $key, int $size, string|null $message = null)
 * @method static \YukataRm\Laravel\Validation\Interface\ValidationRulesInterface startsWith(string $key, array|string $values, string|null $message = null)
 * @method static \YukataRm\Laravel\Validation\Interface\ValidationRulesInterface string(string $key, string|null $message = null)
 * @method static \YukataRm\Laravel\Validation\Interface\ValidationRulesInterface timezone(string $key, array|string $identifiers = [], string|null $message = null)
 * @method static \YukataRm\Laravel\Validation\Interface\ValidationRulesInterface unique(string $key, string $table, string|null $column = null, \Closure|null $callback = null, string|null $message = null)
 * @method static \YukataRm\Laravel\Validation\Interface\ValidationRulesInterface uppercase(string $key, string|null $message = null)
 * @method static \YukataRm\Laravel\Validation\Interface\ValidationRulesInterface url(string $key, string|null $message = null)
 * @method static \YukataRm\Laravel\Validation\Interface\ValidationRulesInterface ulid(string $key, string|null $message = null)
 * @method static \YukataRm\Laravel\Validation\Interface\ValidationRulesInterface uuid(string $key, string|null $message = null)
 * 
 * @method static \YukataRm\Laravel\Validation\Interface\ValidationRulesInterface flag(string $key, string|null $message = null)
 * @method static \YukataRm\Laravel\Validation\Interface\ValidationRulesInterface asDate(string $key, string|null $message = null)
 * @method static \YukataRm\Laravel\Validation\Interface\ValidationRulesInterface asTime(string $key, string|null $message = null)
 * @method static \YukataRm\Laravel\Validation\Interface\ValidationRulesInterface asDateTime(string $key, string|null $message = null)
 * @method static \YukataRm\Laravel\Validation\Interface\ValidationRulesInterface asYearMonth(string $key, string|null $message = null)
 * @method static \YukataRm\Laravel\Validation\Interface\ValidationRulesInterface asMonthDay(string $key, string|null $message = null)
 * @method static \YukataRm\Laravel\Validation\Interface\ValidationRulesInterface asHourMinute(string $key, string|null $message = null)
 * @method static \YukataRm\Laravel\Validation\Interface\ValidationRulesInterface asMinuteSecond(string $key, string|null $message = null)
 * @method static \YukataRm\Laravel\Validation\Interface\ValidationRulesInterface asYear(string $key, string|null $message = null)
 * @method static \YukataRm\Laravel\Validation\Interface\ValidationRulesInterface asMonth(string $key, string|null $message = null)
 * @method static \YukataRm\Laravel\Validation\Interface\ValidationRulesInterface asMonthZero(string $key, string|null $message = null)
 * @method static \YukataRm\Laravel\Validation\Interface\ValidationRulesInterface asMonthName(string $key, string|null $message = null)
 * @method static \YukataRm\Laravel\Validation\Interface\ValidationRulesInterface asMonthNameShort(string $key, string|null $message = null)
 * @method static \YukataRm\Laravel\Validation\Interface\ValidationRulesInterface asDay(string $key, string|null $message = null)
 * @method static \YukataRm\Laravel\Validation\Interface\ValidationRulesInterface asDayZero(string $key, string|null $message = null)
 * @method static \YukataRm\Laravel\Validation\Interface\ValidationRulesInterface asHour(string $key, string|null $message = null)
 * @method static \YukataRm\Laravel\Validation\Interface\ValidationRulesInterface asHourZero(string $key, string|null $message = null)
 * @method static \YukataRm\Laravel\Validation\Interface\ValidationRulesInterface asHourTwelveNotation(string $key, string|null $message = null)
 * @method static \YukataRm\Laravel\Validation\Interface\ValidationRulesInterface asHourTwelveNotationZero(string $key, string|null $message = null)
 * @method static \YukataRm\Laravel\Validation\Interface\ValidationRulesInterface asMinute(string $key, string|null $message = null)
 * @method static \YukataRm\Laravel\Validation\Interface\ValidationRulesInterface asSecond(string $key, string|null $message = null)
 * @method static \YukataRm\Laravel\Validation\Interface\ValidationRulesInterface existsNotDeleted(string $key, string $table, string|null $column = null, string $deletedAtColumn = "deleted_at", string|null $message = null)
 * @method static \YukataRm\Laravel\Validation\Interface\ValidationRulesInterface existsDeleted(string $key, string $table, string|null $column = null, string $deletedAtColumn = "deleted_at", string|null $message = null)
 * @method static \YukataRm\Laravel\Validation\Interface\ValidationRulesInterface id(string $key, string $table, string|null $message = null)
 * @method static \YukataRm\Laravel\Validation\Interface\ValidationRulesInterface tel(string $key, string|null $message = null)
 * @method static \YukataRm\Laravel\Validation\Interface\ValidationRulesInterface postCode(string $key, string|null $message = null)
 * @method static \YukataRm\Laravel\Validation\Interface\ValidationRulesInterface uniqueNotDeleted(string $key, string $table, string|null $column = null, string $deletedAtColumn = "deleted_at", string|null $message = null)
 * @method static \YukataRm\Laravel\Validation\Interface\ValidationRulesInterface uniqueDeleted(string $key, string $table, string|null $column = null, string $deletedAtColumn = "deleted_at", string|null $message = null)
 * @method static \YukataRm\Laravel\Validation\Interface\ValidationRulesInterface uniqueIgnore(string $key, string $table, string|null $column = null, mixed $ignore = null, string $ignoreColumn = "id", string|null $message = null)
 * @method static \YukataRm\Laravel\Validation\Interface\ValidationRulesInterface uniqueIgnoreNotDeleted(string $key, string $table, string|null $column = null, mixed $ignore = null, string $ignoreColumn = "id", string $deletedAtColumn = "deleted_at", string|null $message = null)
 * @method static \YukataRm\Laravel\Validation\Interface\ValidationRulesInterface uniqueIgnoreDeleted(string $key, string $table, string|null $column = null, mixed $ignore = null, string $ignoreColumn = "id", string $deletedAtColumn = "deleted_at", string|null $message = null)
 * 
 * @see \YukataRm\Laravel\Validation\Facade\Manager
 */
class ValidationRules extends Facade
{
    /** 
     * Facade Accessor
     * 
     * @return string 
     */
    protected static function getFacadeAccessor(): string
    {
        return static::class;
    }
}
